# Spring Datasource (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: "jdbc:h2:mem:my_db"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: "password"
    name: "my_db"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"
  config:
    activate:
      on-profile: dev

